/*
 * This header is automatically generated by the configuation
 * script. Please use the configuation script instead of editing
 * this file directly.
 */

#ifndef MSP_CONFIGURATION_H
#define MSP_CONFIGURATION_H

#define MSP_EXP_MTU 507
#define MSP_EXP_ADDR 0x35

#endif
